apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-app
  labels:
    app: diabetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-app
  template:
    metadata:
      labels:
        app: diabetes-app
    spec:
      containers:
      - name: diabetes-app
        image: danial92gh/fastapi-diabetes-jenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000