apiVersion: v1
kind: Service
metadata:
  name: diabetes-predictor-service
spec:
  selector:
    app: diabetes-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer